'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace UslugaBIRpubl
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ParametryWyszukiwania", [Namespace]:="http://CIS/BIR/PUBL/2014/07/DataContract"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ParametryWyszukiwania
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KrsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KrsyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NipField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NipyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Regony14znField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Regony9znField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Krs() As String
            Get
                Return Me.KrsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KrsField, value) <> true) Then
                    Me.KrsField = value
                    Me.RaisePropertyChanged("Krs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Krsy() As String
            Get
                Return Me.KrsyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KrsyField, value) <> true) Then
                    Me.KrsyField = value
                    Me.RaisePropertyChanged("Krsy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nip() As String
            Get
                Return Me.NipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NipField, value) <> true) Then
                    Me.NipField = value
                    Me.RaisePropertyChanged("Nip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nipy() As String
            Get
                Return Me.NipyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NipyField, value) <> true) Then
                    Me.NipyField = value
                    Me.RaisePropertyChanged("Nipy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Regon() As String
            Get
                Return Me.RegonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegonField, value) <> true) Then
                    Me.RegonField = value
                    Me.RaisePropertyChanged("Regon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Regony14zn() As String
            Get
                Return Me.Regony14znField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Regony14znField, value) <> true) Then
                    Me.Regony14znField = value
                    Me.RaisePropertyChanged("Regony14zn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Regony9zn() As String
            Get
                Return Me.Regony9znField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Regony9znField, value) <> true) Then
                    Me.Regony9znField = value
                    Me.RaisePropertyChanged("Regony9zn")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://CIS/BIR/PUBL/2014/07", ConfigurationName:="UslugaBIRpubl.IUslugaBIRzewnPubl")>  _
    Public Interface IUslugaBIRzewnPubl
        
        'CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (http://CIS/BIR/2014/07) komunikatu PobierzCaptchaRequest nie pasuje do domyślnej wartości (http://CIS/BIR/PUBL/2014/07).
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptcha", ReplyAction:="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptchaResponse")>  _
        Function PobierzCaptcha(ByVal request As UslugaBIRpubl.PobierzCaptchaRequest) As UslugaBIRpubl.PobierzCaptchaResponse
        
        'CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (http://CIS/BIR/2014/07) komunikatu SprawdzCaptchaRequest nie pasuje do domyślnej wartości (http://CIS/BIR/PUBL/2014/07).
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptcha", ReplyAction:="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptchaResponse")>  _
        Function SprawdzCaptcha(ByVal request As UslugaBIRpubl.SprawdzCaptchaRequest) As UslugaBIRpubl.SprawdzCaptchaResponse
        
        'CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (http://CIS/BIR/2014/07) komunikatu SetValueRequest nie pasuje do domyślnej wartości (http://CIS/BIR/PUBL/2014/07).
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/2014/07/IUslugaBIR/SetValue", ReplyAction:="http://CIS/BIR/2014/07/IUslugaBIR/SetValueResponse")>  _
        Function SetValue(ByVal request As UslugaBIRpubl.SetValueRequest) As UslugaBIRpubl.SetValueResponse
        
        'CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (http://CIS/BIR/2014/07) komunikatu GetValueRequest nie pasuje do domyślnej wartości (http://CIS/BIR/PUBL/2014/07).
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/2014/07/IUslugaBIR/GetValue", ReplyAction:="http://CIS/BIR/2014/07/IUslugaBIR/GetValueResponse")>  _
        Function GetValue(ByVal request As UslugaBIRpubl.GetValueRequest) As UslugaBIRpubl.GetValueResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj", ReplyAction:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/ZalogujResponse")>  _
        Function Zaloguj(ByVal pKluczUzytkownika As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj", ReplyAction:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/WylogujResponse")>  _
        Function Wyloguj(ByVal pIdentyfikatorSesji As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukaj", ReplyAction:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajResponse")>  _
        Function DaneSzukaj(ByVal pParametryWyszukiwania As UslugaBIRpubl.ParametryWyszukiwania) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport", ReplyAction:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaportResponse")>  _
        Function DanePobierzPelnyRaport(ByVal pRegon As String, ByVal pNazwaRaportu As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikat", ReplyAction:="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikatResponse")>  _
        Function DaneKomunikat() As String
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PobierzCaptcha", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class PobierzCaptchaRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PobierzCaptchaResponse", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class PobierzCaptchaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=0)>  _
        Public PobierzCaptchaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PobierzCaptchaResult As String)
            MyBase.New
            Me.PobierzCaptchaResult = PobierzCaptchaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="SprawdzCaptcha", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class SprawdzCaptchaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=0)>  _
        Public pCaptcha As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pCaptcha As String)
            MyBase.New
            Me.pCaptcha = pCaptcha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="SprawdzCaptchaResponse", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class SprawdzCaptchaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=0)>  _
        Public SprawdzCaptchaResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SprawdzCaptchaResult As Boolean)
            MyBase.New
            Me.SprawdzCaptchaResult = SprawdzCaptchaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="SetValue", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class SetValueRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=0)>  _
        Public pNazwaParametru As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=1)>  _
        Public pWartoscParametru As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pNazwaParametru As String, ByVal pWartoscParametru As String)
            MyBase.New
            Me.pNazwaParametru = pNazwaParametru
            Me.pWartoscParametru = pWartoscParametru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="SetValueResponse", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class SetValueResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=0)>  _
        Public SetValueResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SetValueResult As String)
            MyBase.New
            Me.SetValueResult = SetValueResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetValue", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class GetValueRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=0)>  _
        Public pNazwaParametru As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pNazwaParametru As String)
            MyBase.New
            Me.pNazwaParametru = pNazwaParametru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetValueResponse", WrapperNamespace:="http://CIS/BIR/2014/07", IsWrapped:=true)>  _
    Partial Public Class GetValueResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://CIS/BIR/2014/07", Order:=0)>  _
        Public GetValueResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetValueResult As String)
            MyBase.New
            Me.GetValueResult = GetValueResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IUslugaBIRzewnPublChannel
        Inherits UslugaBIRpubl.IUslugaBIRzewnPubl, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UslugaBIRzewnPublClient
        Inherits System.ServiceModel.ClientBase(Of UslugaBIRpubl.IUslugaBIRzewnPubl)
        Implements UslugaBIRpubl.IUslugaBIRzewnPubl
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UslugaBIRpubl_IUslugaBIRzewnPubl_PobierzCaptcha(ByVal request As UslugaBIRpubl.PobierzCaptchaRequest) As UslugaBIRpubl.PobierzCaptchaResponse Implements UslugaBIRpubl.IUslugaBIRzewnPubl.PobierzCaptcha
            Return MyBase.Channel.PobierzCaptcha(request)
        End Function
        
        Public Function PobierzCaptcha() As String
            Dim inValue As UslugaBIRpubl.PobierzCaptchaRequest = New UslugaBIRpubl.PobierzCaptchaRequest()
            Dim retVal As UslugaBIRpubl.PobierzCaptchaResponse = CType(Me,UslugaBIRpubl.IUslugaBIRzewnPubl).PobierzCaptcha(inValue)
            Return retVal.PobierzCaptchaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UslugaBIRpubl_IUslugaBIRzewnPubl_SprawdzCaptcha(ByVal request As UslugaBIRpubl.SprawdzCaptchaRequest) As UslugaBIRpubl.SprawdzCaptchaResponse Implements UslugaBIRpubl.IUslugaBIRzewnPubl.SprawdzCaptcha
            Return MyBase.Channel.SprawdzCaptcha(request)
        End Function
        
        Public Function SprawdzCaptcha(ByVal pCaptcha As String) As Boolean
            Dim inValue As UslugaBIRpubl.SprawdzCaptchaRequest = New UslugaBIRpubl.SprawdzCaptchaRequest()
            inValue.pCaptcha = pCaptcha
            Dim retVal As UslugaBIRpubl.SprawdzCaptchaResponse = CType(Me,UslugaBIRpubl.IUslugaBIRzewnPubl).SprawdzCaptcha(inValue)
            Return retVal.SprawdzCaptchaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UslugaBIRpubl_IUslugaBIRzewnPubl_SetValue(ByVal request As UslugaBIRpubl.SetValueRequest) As UslugaBIRpubl.SetValueResponse Implements UslugaBIRpubl.IUslugaBIRzewnPubl.SetValue
            Return MyBase.Channel.SetValue(request)
        End Function
        
        Public Function SetValue(ByVal pNazwaParametru As String, ByVal pWartoscParametru As String) As String
            Dim inValue As UslugaBIRpubl.SetValueRequest = New UslugaBIRpubl.SetValueRequest()
            inValue.pNazwaParametru = pNazwaParametru
            inValue.pWartoscParametru = pWartoscParametru
            Dim retVal As UslugaBIRpubl.SetValueResponse = CType(Me,UslugaBIRpubl.IUslugaBIRzewnPubl).SetValue(inValue)
            Return retVal.SetValueResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UslugaBIRpubl_IUslugaBIRzewnPubl_GetValue(ByVal request As UslugaBIRpubl.GetValueRequest) As UslugaBIRpubl.GetValueResponse Implements UslugaBIRpubl.IUslugaBIRzewnPubl.GetValue
            Return MyBase.Channel.GetValue(request)
        End Function
        
        Public Function GetValue(ByVal pNazwaParametru As String) As String
            Dim inValue As UslugaBIRpubl.GetValueRequest = New UslugaBIRpubl.GetValueRequest()
            inValue.pNazwaParametru = pNazwaParametru
            Dim retVal As UslugaBIRpubl.GetValueResponse = CType(Me,UslugaBIRpubl.IUslugaBIRzewnPubl).GetValue(inValue)
            Return retVal.GetValueResult
        End Function
        
        Public Function Zaloguj(ByVal pKluczUzytkownika As String) As String Implements UslugaBIRpubl.IUslugaBIRzewnPubl.Zaloguj
            Return MyBase.Channel.Zaloguj(pKluczUzytkownika)
        End Function
        
        Public Function Wyloguj(ByVal pIdentyfikatorSesji As String) As Boolean Implements UslugaBIRpubl.IUslugaBIRzewnPubl.Wyloguj
            Return MyBase.Channel.Wyloguj(pIdentyfikatorSesji)
        End Function
        
        Public Function DaneSzukaj(ByVal pParametryWyszukiwania As UslugaBIRpubl.ParametryWyszukiwania) As String Implements UslugaBIRpubl.IUslugaBIRzewnPubl.DaneSzukaj
            Return MyBase.Channel.DaneSzukaj(pParametryWyszukiwania)
        End Function
        
        Public Function DanePobierzPelnyRaport(ByVal pRegon As String, ByVal pNazwaRaportu As String) As String Implements UslugaBIRpubl.IUslugaBIRzewnPubl.DanePobierzPelnyRaport
            Return MyBase.Channel.DanePobierzPelnyRaport(pRegon, pNazwaRaportu)
        End Function
        
        Public Function DaneKomunikat() As String Implements UslugaBIRpubl.IUslugaBIRzewnPubl.DaneKomunikat
            Return MyBase.Channel.DaneKomunikat
        End Function
    End Class
End Namespace
